name: Publish App

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: windows-latest
    permissions: 
      contents: write
      
    strategy:
      matrix:
        arch: [ia32, x64]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.11.1"
          registry-url: "https://registry.npmjs.org"

      - name: Install
        run: |
          npm i

      - name: Compile TypeScript
        run: |
          npx tsc

      - name: Build for ${{ matrix.arch }}
        run: |
          npx electron-forge make --arch="${{ matrix.arch }}"

      - name: Publish
        run: |
          npm run publish
        env:
          GITHUB_TOKEN: ${{ github.token }}